openapi: 3.0.0

info:
  title: AlienVault
  description: This plugin will provide the functionality to fetch the details of an IP address using the AlienVault.
  version: "1.0.0"

servers:
  - url: https://otx.alienvault.com/api/v1/indicators/

paths:
  /IPv4/{ip}/general/:
    get:
      operationId: AlienVault - Get Generic Details About IP
      summary: This skill will search for the IP address and get the details about the it if it was involved in any suspicious activities using AlienVault.
      parameters:
        - in: path
          name: ip
          schema:
            type: string
          required: true
          description: Get the IP address to lookup in AlienVault.
      responses:
        "200":
          description: OK
  /IPv4/{ip}/malware/:
    get:
      operationId: AlienVault - Get Malware Details About IP
      summary: This skill will search for the IP address and get the details about the it if it was involved in any malware related activities using AlienVault.
      parameters:
        - in: path
          name: ip
          schema:
            type: string
          required: true
          description: Get the IP address to lookup in AlienVault.
      responses:
        "200":
          description: OK
  /IPv4/{ip}/geo/:
    get:
      operationId: AlienVault - Get Geo Details About IP
      summary: This skill will search for the IP address and get the details about the it if it was involved in any malware related activities using AlienVault.
      parameters:
        - in: path
          name: ip
          schema:
            type: string
          required: true
          description: Get the IP address to lookup in AlienVault.
      responses:
        "200":
          description: OK
  /hostname/{hostname}/general/:
    get:
      operationId: AlienVault - Get Domain Details
      summary: This skill will search for the domain name and get the details about the it if it was involved in any suspicious activities using AlienVault.
      parameters:
        - in: path
          name: hostname
          schema:
            type: string
          required: true
          description: Enter the domain to lookup in AlienVault.
      responses:
        "200":
          description: OK
  /file/{file_hash}/general/:
    get:
      operationId: AlienVault - Get File Hash Details
      summary: This skill will search for the filehases and get the details about the it if it was involved in any suspicious activities using AlienVault.
      parameters:
        - in: path
          name: file_hash
          schema:
            type: string
          required: true
          description: Enter the filehash to lookup in AlienVault.
      responses:
        "200":
          description: OK
  /url/{url}/general:
    get:
      operationId: AlienVault - Get URL Details
      summary: This skill will search for the URL and get the general details about the it if it was involved in any suspicious activities using AlienVault.
      parameters:
        - in: path
          name: url
          schema:
            type: string
          required: true
          description: Enter the URL to lookup in AlienVault.
      responses:
        "200":
          description: OK
