openapi: 3.0.0

info:
    title: Microsoft Defender - Threat Intelligence Indicators - Extension
    description: Microsoft Defender - Threat Intelligence Indicators - Extension
    version: "beta"

servers:
    - url: https://graph.microsoft.com/beta

paths:
    /security/tiIndicators:
        post:
            operationId: MDTI - Add Indicators
            summary: This skill will add a potential IOC (IP Address, DomainName, URL, FIleHash) as the Threat Intelligence Indicator. Required fields are -> action, and one of these following values -> domainName, url, networkIPv4, fileHashValue (must supply fileHashType in case of fileHashValue).
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                action:
                                    type: string
                                    default: block
                                    enum: 
                                        - unknown
                                        - allow
                                        - block
                                        - alert
                                    description: The action to apply if the indicator is matched from within the targetProduct security tool. Possible values are -> unknown, allow, block, alert. Required.
                                description:
                                    type: string
                                    default : Adding a Potential IOCs from 
                                    description: Brief description (100 characters or less) of the threat represented by the indicator. Required.
                                threatType:
                                    type: string
                                    default : Malware
                                    enum: 
                                        - Botnet
                                        - C2
                                        - CrypotoMining
                                        - Darknet
                                        - DDoS
                                        - MaliciousUrl
                                        - Malware
                                        - Phishing
                                        - Proxy
                                        - PUA
                                        - WatchList
                                    description: Each indicator must have a valid Indicator Threat Type. Possible values are -> Botnet, C2, CryptoMining, Darknet, DDoS, MaliciousUrl, Malware, Phishing, Proxy, PUA, WatchList. Default set to Malware
                                targetProduct:
                                    type: string
                                    default : Microsoft Defender ATP
                                    description: A string value representing a single security product to which the indicator should be applied. Acceptable values are -> Azure Sentinel, Microsoft Defender ATP. Default set to Microsoft Defender ATP.
                                domainName:
                                    type: string
                                    description: Domain name associated with this indicator. Should be of the format subdomain.domain.topleveldomain (For example, baddomain.domain.net)
                                url:
                                    type: string
                                    description: Uniform Resource Locator which you want to add in the TI. This URL must comply with RFC 1738.
                                networkIPv4:
                                    type: string
                                    description: IPv4 IP address.
                                fileHashType:
                                    type: string
                                    enum: 
                                        - unknown
                                        - sha1
                                        - sha256
                                        - md5
                                        - authenticodeHash256
                                        - lsHash
                                        - ctph
                                    description: The type of hash stored in fileHashValue. Possible values are -> unknown, sha1, sha256, md5, authenticodeHash256, lsHash, ctph.
                                fileHashValue:
                                    type: string
                                    description: The file hash value.
                                tlpLevel:
                                    type: string
                                    default: red
                                    enum: 
                                        - unknown
                                        - white
                                        - green
                                        - amber
                                        - red
                                    description: Traffic Light Protocol value for the indicator. Possible values are -> unknown, white, green, amber, red. This field is required. The default value is red.
                                confidence:
                                    type: integer
                                    default : 75
                                    description: An integer representing the confidence the data within the indicator accurately identifies malicious behavior. Acceptable values are 0 - 100 with 100 being the highest. Default set to 75.
                                expirationDateTime:
                                    type: string
                                    format: date-time
                                    example: 2017-07-21T17:32:28Z
                                    description: Enter the expiration time of the indicator.
                                severity:
                                    type: integer
                                    default : 3
                                    enum: 
                                        - 1
                                        - 2
                                        - 3
                                        - 4
                                        - 5
                                    description: An integer representing the severity of the malicious behavior identified by the data within the indicator. Acceptable values are 0 - 5 where 5 is the most severe and zero isn't severe at all. Default value is 3. Default set to 3
                            required:
                                - action
                                - description
                                - tlpLevel
                                - confidence
            responses:
                "200":
                    description: OK
