openapi: 3.0.0

info:
    title: Microsoft Defender - Extension
    description: Microsoft Defender - Extension
    version: "beta"

servers:
    - url: https://graph.microsoft.com/beta

paths:
    /security/tiIndicators:
        get:
            operationId: Check TI Database - Defender
            description: Check if an IOC exists in a company database Microsoft Defender.
            parameters:
                - in: query
                  name: $filter
                  schema:
                      type: string
                  required: false
                  description: A filter in the format of "fileHashValue eq <filehash>" where filehash is the value of the filehash you want to check.
                - in: query
                  name: $top
                  schema:
                      type: integer
                  required: false
                  description: Get top n number of IOCs from the database of your organization on Microsoft Defender.
            responses:
                "200":
                    description: OK
