openapi: 3.0.0

info:
    title: Microsoft Defender - SuperExtention
    description: Microsoft Defender - SuperExtention
    version: "v1"

servers:
    - url: https://api.securitycenter.microsoft.com/api

paths:
    /machines/{id}/isolate:
        post:
            operationId: Defender XDR - Isolate a Machine
            summary: This skill will Isolates a device from accessing external network.
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  required: true
                  description: The id of the machine you want to isolate.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                Comment:
                                    type: string
                                    default : Blocking a machine from Copilot.
                                    description: A string value representing an appropriate comment for machine isolation.
                                IsolationType:
                                    type: string
                                    enum: 
                                        - Full
                                        - Selective
                                    description: Type of the isolation. Allowed values are 'Full' or 'Selective'.
                            required:
                                - Comment
                                - IsolationType
            responses:
                "200":
                    description: OK
                "201":
                    description: Successfully created the Indicator
    /machines/{id}/unisolate:
        post:
            operationId: Defender XDR - Un-isolate a Machine
            summary: This skill will Un-isolate a device from accessing external network.
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  required: true
                  description: The id of the machine you want to un-isolate.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                Comment:
                                    type: string
                                    default : Blocking a machine from Copilot.
                                    description: A string value representing an appropriate comment for machine isolation.
                            required:
                                - Comment
            responses:
                "200":
                    description: OK
                "201":
                    description: Successfully created the Indicator
    /machines:
        get:
            operationId: Defender XDR - Get Machine Details
            description: Get Machine details which is onboarded on the Microsoft Defender XDR.
            parameters:
                - in: query
                  name: $filter
                  schema:
                      type: string
                  required: false
                  example: contains(computerDnsName, 'Desktop-Parth')
                  description: A filter to get your machine. Make sure to format it like following. contains(computerDnsName, 'Desktop-Parth')
            responses:
                "200":
                    description: OK
    /machines/{id}/restrictCodeExecution:
        post:
            operationId: Defender XDR - Restrict app execution
            summary: This skill will restrict any third-party app execution on device.
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  required: true
                  description: The id of the machine you want to Restrict app execution.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                Comment:
                                    type: string
                                    default : Restricting app execution from Copilot.
                                    description: A string value representing an appropriate comment for Restricting app execution.
                            required:
                                - Comment
            responses:
                "200":
                    description: OK
                "201":
                    description: Successfully created the Indicator
    /machines/{id}/unrestrictCodeExecution:
        post:
            operationId: Defender XDR - Remove app restriction
            summary: This skill will remove restricion of any third-party app on device which is onboarded to Microsoft Defender XDR.
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  required: true
                  description: The id of the machine you want to release from restriction of app execution.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                Comment:
                                    type: string
                                    default : Restricting app execution from Copilot.
                                    description: A string value representing an appropriate comment for releasing a machine from App exection.
                            required:
                                - Comment
            responses:
                "200":
                    description: OK
                "201":
                    description: Successfully created the Indicator
    /machines/{id}/runAntiVirusScan:
        post:
            operationId: Defender XDR - Run Anti-Virus Scan
            summary: This skill initiate the process to start Full or Quick scan on a device which is onboarded to Microsoft Defender XDR.
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  required: true
                  description: The id of the machine you want to run the anti virus scan on.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ScanType:
                                    type: string
                                    default : Quick
                                    enum: 
                                        - Quick
                                        - Full
                                    description: Defines the type of the Scan.
                                Comment:
                                    type: string
                                    default : Restricting app execution from Copilot.
                                    description: A string value representing an appropriate comment for running a scan on machine.
                            required:
                                - Comment
                                - ScanType
            responses:
                "200":
                    description: OK
                "201":
                    description: Successful
    /machines/{id}/runAntiVirusScan:
        post:
            operationId: Defender XDR - Stop and quarantine file
            summary: This skill initiate the process to Stop execution of a file on a device and delete it.
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  required: true
                  description: The id of the machine you want to Stop execution of a file on a device and delete it.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                Sha1:
                                    type: string
                                    description: Input the sha1 of the file which you want to Stop execution of on a device and delete it.
                                Comment:
                                    type: string
                                    default : Quarantining a file as it was detected suspicious after the analysis.
                                    description: A string value representing an appropriate comment for quarantining the file.
            responses:
                "200":
                    description: OK
                "201":
                    description: Successful
