openapi: 3.0.0

info:
    title: Microsoft Entra ID - Reset User Password
    description: Microsoft Entra ID - Reset User Password
    version: "v1"

servers:
    - url: https://graph.microsoft.com/v1.0

paths:
    /users/{userPrincipalName}:
        patch:
            operationId: Entra ID - Reset a User Password
            summary: This skill will reset a user password.
            parameters:
                - in: path
                  name: userPrincipalName
                  schema:
                      type: string
                  required: true
                  description: The userPrincipalName whose password you want to reset.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                passwordProfile:
                                    type: object
                                    properties:
                                        forceChangePasswordNextSignIn:
                                            type: boolean
                                            default: false
                                            enum:
                                                - true
                                                - false
                                            description: Set the value "true" if the user must change their password on the next sign-in; otherwise "false". If not set, default is false.
                                        password:
                                            type: string
                                    description: Set the passwordProfile for a user.
                            required: true
            responses:
                "200":
                    description: OK
                "204":
                    description: Successful
