openapi: 3.0.0

info:
    title: Hybrid-Analysis Reports
    description: Hybrid-Analysis Reports
    version: "v2"

servers:
    - url: https://hybrid-analysis.com/api/v2
    
paths:
    /search/hash:
        post:
            operationId: HAFileHashReport
            summary: Lookup a filehash for information on HybridAnalysis.
            requestBody:
              description: Defining requestbody.
              required: true
              content:
                application/x-www-form-urlencoded:
                  schema:
                    type: object
                    properties:
                      hash:
                        type: string
                        description: The hash value to search for
            responses:
              "200":
                description: OK
