openapi: 3.0.0

info:
    title: Defender Threat Intelligence Indicator
    description: Defender Threat Intelligence Indicator
    version: "beta"

servers:
    - url: https://graph.microsoft.com

paths:
    /beta/security/tiIndicators?$filter=fileHashValue+eq+'{filehash}':
        get:
            operationId: Check FileHash TI on Defender
            description: Check if the filehash exists in a company database of IOCs of Microsoft Defender.
            parameters:
                - in: path
                  name: filehash
                  schema:
                      type: string
                  required: true
                  description: A filter in the format of "fileHashValue eq <filehash>" where filehash is the value of the filehash you want to check.
            responses:
                "200":
                    description: OK
    /beta/security/alerts_v2?$filter=severity+eq+'{severity}':
        get:
            operationId: Get Alerts of a specific severity
            description: Gets Alerts of a specific severity.
            parameters:
                - in: path
                  name: severity
                  schema:
                      type: string
                  required: true
                  description: choose severity from Informational, Low, Medium, High.
            responses:
                "200":
                    description: OK
