openapi: 3.0.0

info:
    title: Defender Threat Intelligence Indicator
    description: Defender Threat Intelligence Indicator
    version: "beta"

servers:
    - url: https://graph.microsoft.com

paths:
    /beta/security/tiIndicators:
        get:
            operationId: Check FileHash TI on Defender
            description: Check if the filehash exists in a company database of IOCs of Microsoft Defender.
            parameters:
                - in: path
                  name: $filter
                  schema:
                      type: string
                  required: true
                  description: A filter in the format of "fileHashValue eq <filehash>" where filehash is the value of the filehash you want to check.
            responses:
                "200":
                    description: OK
    /beta/security/alerts_v2:
        get:
            operationId: Get Alerts of a specific severity
            description: Gets Alerts of a specific severity.
            parameters:
                - in: query
                  name: $filter
                  schema:
                      type: string
                  required: true
                  description: Write your query in the given format. severity eq '<severity>'
                - in: query
                  name: $select
                  schema:
                      type: string
                  required: true
                  description: Choose any fields from the given and make sure to pass them separated by commas like given in the example. (eg. id,title,description,category,recommendedActions,alertWebUrl,createdDateTime,lastUpdateDateTime)
            responses:
                "200":
                    description: OK
