openapi: 3.0.0

info:
  title: AbuseIPDB.com
  description: This plugin will provide the functionality to fetch the details of an IP address using the AbuseIPDB.
  version: "v2"

servers:
  - url: https://www.abuseipdb.com/

paths:
  /check/{ipAddress}:
    get:
        operationId: ABIPCheckReport
        parameters:
          - in: path
            name: ipAddress
            required: true
            schema:
              type: string
          - in: path
            name: maxAgeInDays
            schema:
              type: integer
            example: 90
        responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  type: object
