openapi: 3.0.0

info:
    title: PulseDive Reports
    description: PulseDive Reports
    version: "v1"

servers:
    - url: https://pulsedive.com/api

paths:
    /info.php:
        get:
            operationId: PulseDive - Indicator Report
            summary: Lookup Indicator information
            parameters:
                - in: query
                  name: indicator
                  schema:
                      type: string
                  required: true
                  description: The indicator to lookup on Pulsedive
                - in: query
                  name: pretty
                  schema:
                      type: string
                      default : 1
                  required: false
            responses:
                "200":
                    description: OK
    /analyze.php:
        post:
            operationId: PulseDive - Indicator Submission
            summary: Indicator information
            requestBody:
                required: true
                content:
                    application/x-www-form-urlencoded:
                        schema:
                            type: object
                            properties:
                                value:
                                    type: string
                                    description: The indicator to submit on Pulsedive.
                                probe:
                                    type: string
                                    default : 1
                                    description: Default set to 1
                                pretty:
                                    type: string
                                    default : 1
                                    description: Default set to 1
                            required:
                                - value
            responses:
                "200":
                    description: OK
