openapi: 3.0.0

info:
    title: Subdomain Scan
    description: This plugin will get you the subdomains of the domain you query.
    version: "v1"

servers:
    - url: https://subdomain-scan1.p.rapidapi.com/

paths:
    /:
        get:
            operationId: Subdomain Scan - Get the subdomains
            summary: Lookup subdomains information
            parameters:
                - in: query
                  name: domain
                  schema:
                      type: string
                  required: true
                  description: The domain address to lookup
                - in: query
                  name: x-rapidapi-host
                  schema:
                      type: string
                      default: subdomain-scan1.p.rapidapi.com
                  required: false
                  description: Endpoint of the api. (No need to enter anything in this box)
            responses:
                "200":
                    description: OK
