openapi: 3.0.0

info:
  title: Hybrid Analysis
  description: This plugin will provide the functionality to fetch the details of files and URLs from Hybrid Analysis.
  version: "v2"

servers:
  - url: https://hybrid-analysis.com/

paths:
  /api/v2/overview/{sha256}:
    get:
      operationId: Hybrid Analysis File Hash Overview
      summary: This skill will search for the provided sha256 hash value and get the details about the hash if it was involved in any of the malicious activity from the HybridAnalysis.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Input sha256 hash vaule to lookup in Hybrid Analysis.
      responses:
        "200":
          description: OK 
          content:
            application/json:
              schema:
                type: object
  /api/v2/overview/{sha256}/summary:
    get:
      operationId: Hybrid Analysis File Hash Summary
      summary: This skill will search for the provided sha256 hash value and get the summary of the same.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Input sha256 hash vaule to lookup in Hybrid Analysis.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
