openapi: 3.0.0
info:
  title: AbuseIPDB API
  description: API for checking information about IP addresses using AbuseIPDB
  version: "2.0.0"
servers:
  - url: https://api.abuseipdb.com/api/v2/
paths:
  /check:
    get:
      summary: Check IP address information
      description: |
        Check information about a given IP address.
      parameters:
        - name: ipAddress
          in: query
          description: IP address to check.
          required: true
          schema:
            type: string
        - name: maxAgeInDays
          in: query
          description: Maximum age of reports to consider (in days).
          required: false
          schema:
            type: integer
            minimum: 90
            maximum: 100
            default: 90
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
