openapi: 3.0.0

info:
  title: Hybrid Analysis
  description: This plugin will provide the functionality to fetch the details of files and URLs from Hybrid Analysis.
  version: "v2"

servers:
  - url: https://hybrid-analysis.com/

paths:
  /api/v2/quick-scan/url:
    post:
      operationId: Hybrid Analysis quick scan URL.
      summary: This skill will get the report of a URL by posting it into the hybrid-analysis engine.
      description: This skill will get the report of a URL by posting it into the hybrid-analysis engine.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                scan_type:
                  type: string
                  description: The type of scan you want to perform.
                  enum: 
                    - all
                    - all_scan
                    - all_lookup
                    - lookup_ha
                    - lookup_whitelists
                    - lookup_whitelists_internal
                    - lookup_cleandns
                    - lookup_bforeai
                    - scan_crowdstrike_ml
                    - scan_metadefender
                    - scan_urlscanio
                    - scan_scamadviser
                url:
                  type: string
                  description: The URL which you want to scan.
                comment:
                  type: string
                  description: Comment
                submit_name:
                  type: string
                  description: Optional submission name field that will be used for file type detection and analysis
              required:
                - scan_type
                - url
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request parameters
  /api/v2/overview/{sha256}:
    get:
      operationId: Hybrid Analysis File Hash Overview
      summary: This skill will search for the provided sha256 hash value and get the details about the hash if it was involved in any of the malicious activity from the HybridAnalysis.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Input sha256 hash vaule to lookup in Hybrid Analysis.
      responses:
        "200":
          description: OK 
          content:
            application/json:
              schema:
                type: object
  /api/v2/overview/{sha256}/summary:
    get:
      operationId: Hybrid Analysis File Hash Summary
      summary: This skill will search for the provided sha256 hash value and get the summary of the same.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Input sha256 hash vaule to lookup in Hybrid Analysis.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
