openapi: 3.0.0

info:
  title: AbuseIPDB.com
  description: This plugin will provide the functionality to fetch the details of an IP address using the AbuseIPDB.
  version: "v2"

servers:
  - url: https://api.abuseipdb.com/api/v2/

paths:
  /check:
    get:
      operationId: GetIPReputation
      summary: Get Information about the IP address.
      parameters:
        - in: query
          name: ipAddress
          schema:
            type: string
          required: true
        - in: query
          maxAgeInDays: 90
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  ipAddress:
                    type: string
                  abuseConfidenceScore:
                    type: integer
                  country:
                    type: string
                  countryCode:
                    type: string
                  usageType:
                    type: string
                  isp:
                    type: string
                  domain:
                    type: string
                  totalReports:
                    type: integer
                  numDistinctUsers:
                    type: integer
                  lastReportedAt:
                    type: string
                    format: date-time
          description: Successful response
