openapi: 3.0.0

info:
  title: AbuseIPDB.com
  description: This plugin will provide the functionality to fetch the details of an IP address using the AbuseIPDB.
  version: "2.0.0"

servers:
  - url: https://api.abuseipdb.com/

paths:
  /api/v2/check:
    get:
      operationId: GetIPReputation
      summary: Get Information about the IP address.
      parameters:
        - in: query
          name: ipAddress
          schema:
            type: string
          description: The IP address to check.
          required: true
        - in: query
          name: maxAgeInDays
          schema:
            type: integer
          description: Maximum age of reports to consider, in days (default: 90).
          required: false
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad request
