openapi: 3.0.0

info:
  title: Hybrid Analysis
  description: This plugin will provide the functionality to fetch the details of files and URLs from Hybrid Analysis.
  version: "v2"

servers:
  - url: https://hybrid-analysis.com/api/v2/

paths:
  /quick-scan/url:
    post:
      operationId: Hybrid Analysis - Quick scan URL
      summary: This skill will get the report of a URL by posting it into the hybrid-analysis engine.
      description: This skill will get the report of a URL by posting it into the hybrid-analysis engine.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                scan_type:
                  type: string
                  description: The type of scan you want to perform.
                  enum: 
                    - all
                    - all_scan
                    - all_lookup
                    - lookup_ha
                    - lookup_whitelists
                    - lookup_whitelists_internal
                    - lookup_cleandns
                    - lookup_bforeai
                    - scan_crowdstrike_ml
                    - scan_metadefender
                    - scan_urlscanio
                    - scan_scamadviser
                url:
                  type: string
                  description: The URL which you want to scan.
              required:
                - scan_type
                - url
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
  /search/hash:
    post:
      operationId: Hybrid Analysis - Search the hash 
      summary: This skill will get the report of a filehash by posting it into the hybrid-analysis engine. (MD5, SHA256 and SHA1 supported)
      description: This skill will get the report of a filehash by posting it into the hybrid-analysis engine.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                hash:
                  type: string
                  description: The filehash which you want to scan.
              required:
                - hash
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
  /quick-scan/file:
    post:
      operationId: Hybrid Analysis - Get the file report 
      summary: This skill will get the report of a file by uploading it into the hybrid-analysis engine. (MD5, SHA256 and SHA1 supported)
      description: This skill will get the report of a file by uploading it into the hybrid-analysis engine. (MD5, SHA256 and SHA1 supported)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                scan_type:
                  type: string
                  description: The type of scan you want to perform.
                  enum: 
                    - all
                    - all_scan
                    - all_lookup
                    - lookup_ha
                    - lookup_whitelists
                    - lookup_whitelists_internal
                    - lookup_cleandns
                    - lookup_bforeai
                    - scan_crowdstrike_ml
                    - scan_metadefender
                    - scan_urlscanio
                    - scan_scamadviser
                file:
                  type: string
                  format: binary
                  description: The file which you want to scan.
              required:
                - file
                - all
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
  /overview/{sha256}:
    get:
      operationId: Hybrid Analysis - File Hash Overview
      summary: This skill will search for the provided sha256 hash value and get the details about the hash if it was involved in any of the malicious activity from the HybridAnalysis.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Input sha256 hash vaule to lookup in Hybrid Analysis.
      responses:
        "200":
          description: OK 
          content:
            application/json:
              schema:
                type: object
  /overview/{sha256}/summary:
    get:
      operationId: Hybrid Analysis - File Hash Summary
      summary: This skill will search for the provided sha256 hash value and get the summary of the same.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Input sha256 hash vaule to lookup in Hybrid Analysis.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /quick-scan/{id}:
    get:
      operationId: Hybrid Analysis - Get the scan result by ID
      summary: This skill will get the result of a scan by using the ID field.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Input sha256 hash vaule to lookup in Hybrid Analysis.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /feed/{latest}:
    get:
      operationId: Hybrid Analysis - Get the feeds
      summary: This skill will get threat intelligence feed.
      parameters:
        - in: path
          name: latest
          schema:
            type: string
            default: latest
          required: true
          description: latest
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
