openapi: 3.0.0

info:
  title: AbuseIPDB.com
  description: This plugin will provide the functionality to fetch the details of an IP address using the AbuseIPDB.
  version: "2.0.0"

servers:
  - url: https://api.abuseipdb.com/

paths:
  /api/v2/check:
    get:
      operationId: GetIPReputation
      summary: Get Information about the IP address.
      parameters:
        - name: ipAddress
          in: query
          schema:
            type: string
          description: The IP address to check.
          required: true
        - name: maxAgeInDays
          in: query
          schema:
            type: integer
            default: 90
          description: Maximum age of reports to consider, in days (default: 90).
          required: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ipAddress:
                    type: string
                  abuseConfidenceScore:
                    type: integer
                  country:
                    type: string
                  countryCode:
                    type: string
                  usageType:
                    type: string
                  isp:
                    type: string
                  domain:
                    type: string
                  totalReports:
                    type: integer
                  numDistinctUsers:
                    type: integer
                  lastReportedAt:
                    type: string
                    format: date-time
        '400':
          description: Bad request
