openapi: 3.0.0

info:
  title: Hybrid Analysis
  description: This plugin will provide the functionality to fetch the details of files and URLs from Hybrid Analysis.
  version: "v2"

servers:
  - url: https://hybrid-analysis.com/

paths:
  /api/v2/overview/{sha256}:
    get:
      operationId: HAGetFileHashOverview
      summary: This skill will search for the provided sha256 hash value and get the details about the hash if it was involved in any of the malicious activity from the HybridAnalysis.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Get the IP address to lookup in AlienVault.
      reponses:
        "200":
          description: OK
  /api/v2/overview/{sha256}/summary:
    get:
      operationId: HAGetFileHashSummary
      summary: This skill will search for the provided sha256 hash value and get the summary of the same.
      parameters:
        - in: path
          name: sha256
          schema:
            type: string
          required: true
          description: Get the IP address to lookup in AlienVault.
      reponses:
        "200":
          description: OK
