openapi: 3.0.0

info:
  title: AbuseIPDB API
  description: This OpenAPI definition describes the AbuseIPDB API, which allows users to retrieve information about IP addresses reported for abusive behavior.
  version: "v2"
servers:
  - url: https://api.abuseipdb.com/

paths:
  /api/v2/check:
    get:
      summary: Check IP address reputation
      parameters:
        - in: query
          name: ip
          description: The IP address to check.
          required: true
          schema:
            type: string
        - in: query
          name: maxAgeInDays
          description: Maximum age of reports to consider, in days (default: 90).
          required: true
          schema:
            type: integer
            default: 90
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
