openapi: 3.0.0

info:
  title: ThreatFox
  description: ThreatFox is a free platform from abuse.ch with the goal of sharing indicators of compromise (IOCs) associated with malware with the infosec community, AV vendors, and threat intelligence providers.
  version: "v1"

servers:
  - url: https://threatfox-api.abuse.ch/

paths:
  /api/v1/:
    post:
      summary: Get Recent IOCs
      operationId: ThreatFox - Get Recent IOCs
      description: This endpoint enables the user to gather all the Threat Intelligence feed from the ThreatFox platform.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: get_iocs 
                  enum:
                    - get_iocs
                days:
                  type: integer
                  description: Mention Days over here. Make sure it is between 1 to 7.
                  enum:
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                    - 7
                  example: 5
              required:
                - query
                - days
      responses:
        '200':
          description: Successful operation
