openapi: 3.0.0

info:
  title: ThreatFox
  description: ThreatFox is a free platform from abuse.ch with the goal of sharing indicators of compromise (IOCs) associated with malware with the infosec community, AV vendors, and threat intelligence providers.
  version: "v1"

servers:
  - url: https://threatfox-api.abuse.ch/

paths:
  /api/v1/:
    post:
      summary: Get Recent IOCs
      operationId: ThreatFox - Get Recent IOCs
      description: This endpoint enables the user to gather all the Threat Intelligence feed from the ThreatFox platform.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: get_iocs 
                  enum:
                    - get_iocs
                days:
                  type: integer
                  description: Mention Days over here. Make sure it is between 1 to 7.
                  enum:
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                    - 7
                  example: 5
              required:
                - query
                - days
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  query_status:
                    type: string
                    example: ok
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "1275911"
                        ioc:
                          type: string
                          example: jscodecss.com
                        threat_type:
                          type: string
                          example: botnet_cc
                        threat_type_desc:
                          type: string
                          example: Indicator that identifies a botnet command&control server (C&C)
                        ioc_type:
                          type: string
                          example: domain
                        ioc_type_desc:
                          type: string
                          example: Domain that is used for botnet Command&control (C&C)
                        malware:
                          type: string
                          example: unknown
                        malware_printable:
                          type: string
                          example: Unknown malware
                        malware_alias:
                          type: string
                          nullable: true
                          example: null
                        malware_malpedia:
                          type: string
                          example: https://malpedia.caad.fkie.fraunhofer.de/details/unknown
                        confidence_level:
                          type: integer
                          example: 100
                        first_seen:
                          type: string
                          format: date-time
                          example: "2024-05-27 03:49:25 UTC"
                        last_seen:
                          type: string
                          nullable: true
                          example: null
                        reference:
                          type: string
                          example: ""
                        reporter:
                          type: string
                          example: Gi7w0rm
                        tags:
                          type: array
                          items:
                            type: string
                            example: APT
